# name: Auto Upload Uniswap Exchange production build

# on:
#   push:
#     branches:
#       - build-test

# jobs:
#   build_and_upload:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v1
#       - name: Create production build
#         run: |
#           npm install
#           npm run build
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: New Release ${{ github.ref }}
#           draft: false
#           prerelease: false
#       - name: Archive production artifacts
#         uses: actions/upload-artifact@v1
#         with:
#           name: build
#           path: ./build/*
