name: 'Build and upload as release'

on:
  push:
    tags:
      - 'v*'

jobs:
  pre-release:
    name: 'Release'
    runs-on: 'ubuntu-latest'

    steps:
      # ...
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Create production build
        run: |
          npm install
          npm run build
      - name: 'Build & test'
        run: |
          echo "done!"
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          # automatic_release_tag: 'latest'
          prerelease: false
          title: 'Production Build'
          files: |
            ./build/*
